### PR TITLE
Local backend validation#433

### PR DESCRIPTION
**Pull request by ghost**
Fixes #433
Please see the first and second commits. The last one I merged the latest develop to this branch. I think I should have done this after the review.. Will take a lesson from this.

### CODE REVIEW

**Comment by ghost** [comment]
Reviewers: @mcovarr and @francares

**Comment by mcovarr** [comment]
urg, I just merged my stdout/stderr stuff so you'll need a rebase :frowning:  Though at least that should reduce the changes in this PR.

**Comment by ghost** [comment]
Oh! I thought it was already there in develop when I merged it in. 
Either way, no worries about that. I'll merge it again when it's time to merge this in.

**Comment by mcovarr** [comment]
It would be a big help if you could rebase this before review, the vast majority of diffs appear to be unrelated to the changes for this PR.

**Pull request closed without merging**
